import Calculator as c
print("Addition (2 + 3):", c.add(2, 3))
print("Subtraction (5 - 2):", c.subtract(5, 2))
print("Multiplication (4 * 6):", c.multiply(4, 6))
print("Division (10 / 2):", c.divide(10, 2))
print("Value of PI:", c.PI)
print("Square of 5:", c.square(5))
print("Cube of 3:", c.cube(3))
print("Celsius to Fahrenheit: ", c.celsius_to_fahrenheit(0))
print("Fahrenheit to Celsius: ", c.fahrenheit_to_celsius(32))
print("Area of Circle (radius 3):", c.area_of_circle(3))
print("Area of Rectangle (length 4, width 5):", c.area_of_rectangle(4, 5))
print("Area of Triangle (base 6, height 4):", c.area_of_triangle(6, 4))
